### ISSUE TITLE
Issue with Prisma Client  when running Studio

### ISSUE THREAD

**Issue by higajooj** [redwoodjs/studio#36]
I get the following error when running `yarn rw studio`

```
PrismaClientInitializationError: Prisma Client could not locate the Query Engine for runtime "debian-openssl-3.0.x".

This happened because Prisma Client was generated for "darwin-arm64", but the actual deployment required "debian-openssl-3.0.x".
Add "debian-openssl-3.0.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it:

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-3.0.x"]
}

The following locations have been searched:
  /home/daniel/Code/js/brand-new-redwood-v7/node_modules/@redwoodjs/studio/api/db/client
  /Users/tobbe/dev/redwood/studio/api/db/client
  /home/daniel/Code/js/brand-new-redwood-v7/node_modules/@redwoodjs/studio/api/.prisma/client
  /tmp/prisma-engines
  /home/daniel/Code/js/brand-new-redwood-v7/node_modules/@redwoodjs/studio/api/db
    at dl (/home/daniel/Code/js/brand-new-redwood-v7/node_modules/@redwoodjs/studio/api/db/client/runtime/library.js:67:805)
    at async Object.loadLibrary (/home/daniel/Code/js/brand-new-redwood-v7/node_modules/@redwoodjs/studio/api/db/client/runtime/library.js:114:9816)
    at async zt.loadEngine (/home/daniel/Code/js/brand-new-redwood-v7/node_modules/@redwoodjs/studio/api/db/client/runtime/library.js:116:448)
    at async zt.instantiateLibrary (/home/daniel/Code/js/brand-new-redwood-v7/node_modules/@redwoodjs/studio/api/db/client/runtime/library.js:115:10322) {
  clientVersion: '5.7.0',
  errorCode: undefined
}

Node.js v20.11.0
```

I just upgraded my project to Redwood v7. I also created a clean new project using v7, ran `yarn rw studio` and I am getting the same error.

**Comment by higajooj** [comment]
I have a feeling this might be because you guys are using MacBooks. I am running Arch Linux on an i9-9900K. Maybe this is it?

**Comment by Josh-Walker-GM** [comment]
Thanks for raising this issue @higajooj!

I'm definitely suspicious about the `/Users/tobbe/dev/redwood/studio/api/db/client` line... I have access to linux and windows machines too so I will try and see if I can replicate this issue later today.

**Comment by dthyresson** [comment]
Interesting @higajooj .... I hadn't thought about this case given that Studio gets packaged up and the client is generated. Perhaps @Tobbe we may need a way to eject and let people configure the Studio Prisma Client and re-generate it?

**Comment by Tobbe** [comment]
Studio should not ship with pre-built binaries for the prisma client. If that's the case that's clearly a bug 🙂 
@dthyresson Is that what you ment by "this case"?

**Comment by samimozcan** [comment]
```PrismaClientInitializationError: Prisma Client could not locate the Query Engine for runtime "debian-openssl-3.0.x".

This happened because Prisma Client was generated for "darwin-arm64", but the actual deployment required "debian-openssl-3.0.x".
Add "debian-openssl-3.0.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it:

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-3.0.x"]
}

The following locations have been searched:
  /home/saozcan/Projects/ATEZ/sec-web/node_modules/@redwoodjs/studio/api/db/client
  /Users/tobbe/dev/redwood/studio/api/db/client
  /home/saozcan/Projects/ATEZ/sec-web/node_modules/@redwoodjs/studio/api/.prisma/client
  /tmp/prisma-engines
  /home/saozcan/Projects/ATEZ/sec-web/node_modules/@redwoodjs/studio/api/db
    at dl (/home/saozcan/Projects/ATEZ/sec-web/node_modules/@redwoodjs/studio/api/db/client/runtime/library.js:67:805)
    at async Object.loadLibrary (/home/saozcan/Projects/ATEZ/sec-web/node_modules/@redwoodjs/studio/api/db/client/runtime/library.js:114:9816)
    at async zt.loadEngine (/home/saozcan/Projects/ATEZ/sec-web/node_modules/@redwoodjs/studio/api/db/client/runtime/library.js:116:448)
    at async zt.instantiateLibrary (/home/saozcan/Projects/ATEZ/sec-web/node_modules/@redwoodjs/studio/api/db/client/runtime/library.js:115:10322) {
  clientVersion: '5.7.0',
  errorCode: undefined
}

Node.js v20.11.1```

Distro Pop-os

**Comment by Tobbe** [comment]
Looking into this issue more, it seems we *do* include some prisma client code in the release of Studio. It's not in version control, but it does end up in the packaged version of Studio when we release. That's why it has `/Users/tobbe/...` in there – I did the last release

I tried just getting rid of it, but then Studio doesn't even start.

What we need to do is generate the prisma client when Studio is first installed. We just need to figure out how to do that.

**Comment by JALBTCX-PFM-ABE** [comment]
I'm getting a very similar error after upgrading to v7.0.3 (from 6.3.1), but it is for windows.

```
`PrismaClientInitializationError: Prisma Client could not locate the Query Engine for runtime "windows".

This happened because Prisma Client was generated for "darwin-arm64", but the actual deployment required "windows".
Add "windows" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it:

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "windows"]
}

The following locations have been searched:
  C:\Kosmos\node_modules\@redwoodjs\studio\api\db\client
  /Users/tobbe/dev/redwood/studio/api/db/client
  C:\Kosmos\node_modules\@redwoodjs\studio\api\.prisma\client
  /tmp/prisma-engines
  C:\Kosmos\node_modules\@redwoodjs\studio\api\db
    at dl (C:\Kosmos\node_modules\@redwoodjs\studio\api\db\client\runtime\library.js:67:805)
    at async Object.loadLibrary (C:\Kosmos\node_modules\@redwoodjs\studio\api\db\client\runtime\library.js:114:9816)
    at async zt.loadEngine (C:\Kosmos\node_modules\@redwoodjs\studio\api\db\client\runtime\library.js:116:448)
    at async zt.instantiateLibrary (C:\Kosmos\node_modules\@redwoodjs\studio\api\db\client\runtime\library.js:115:10322) {
  clientVersion: '5.7.0',
  errorCode: undefined
}

Node.js v20.11.1
```
I made the changes to prisma.schema that were suggested and the prisma regenerate function and got no errors. 
```
yarn rw prisma generate
```
I still get the same error when I try to run studio.   Has this problem been resolved?

**Comment by Tobbe** [comment]
There's a PR open for it here https://github.com/redwoodjs/studio/pull/44

**Comment by littletuna4** [comment]
Any updates on the release of the fix?

**Comment by higajooj** [comment]
@littletuna4 as a temporary workaround you can build the project yourself and use the latest version.

1. Clone the repo
2. Install dependencies `yarn install`
3. Build `yarn studio:package`
4. Copy the release tarball (`packaged.tgz`) to the root of your project
5. Add the following to your root package.json
  ```
  "resolutions": {
    "@redwoodjs/studio": "./packaged.tgz"
  }
  ```
6. Run `yarn install` on your project to reflect the changes

You can then safely run `yarn rw studio`

A little cumbersome, I know, but this been doing the trick for me for a while.

**Comment by dthyresson** [comment]
Thanks @higajooj for this helpful tip. The team is a bit focussed on RSC at moment, but I hope to jump back into Studio soon and make this a bit cleaner (and publish a new release).
